var http = require('http')
var fs = require('fs')
var url = require('url')
const axios = require('axios');

//Gera página de ator específico
function genAtor(ator) {
    pagHTML = `
    <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Atores</title>
            <link rel="stylesheet" href="w3.css"/>
            <link rel="stylesheet" href="styles.css"/>
        </head>
        
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-green">
                    <h1>${ator.nomeAtor}</h1>
                </header>
        
                <div>
                    <header class="w3-container w3-pale-green">
                        <h3>Informações</h3>
                    </header>
                    <div class="w3-container">
                        <p>Identificador: ${ator.id}</p>
                        <p>Nome: ${ator.nomeAtor}</p>
                        <p>Filmes:</p>
                        <ul>
        `

        if (ator.idFilmes != '') {
            ator.idFilmes.forEach(filme => {

                pagHTML += `                            
                        <li><a href="/filmes/${filme[0]}">${filme[1]}</a></li>
                `
            })
        }

    pagHTML += `        
                        </ul>
                    </div>
                </div>
                <footer class="w3-container w3-green">
                <h6>Generated by EngWeb2024 [<a href="/atores">Voltar à lista de atores</a>]</h6>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

//Gera página de atores
function genAtores(atores) {
    pagHTML = `
    <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Lista de Atores</title>
            <link rel="stylesheet" href="w3.css"/>
            <link rel="stylesheet" href="styles.css"/>
        </head>
        
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-green">
                    <h1>Lista de Atores</h1>
                </header>
        
                <div class="w3-container">
                    <table class="w3-table w3-striped">
                        <thead class="header-green">
                            <tr>
                                <th>Identificador</th>
                                <th>Nome</th>
                                <th>Filmes</th>
                            </tr>
                        </thead>
                        <tbody>
    `
    atores.forEach(ator => {
        pagHTML += `
                        <tr>
                            <td><a href="/atores/${ator.id}">${ator.id}</a></td> 
                            <td>${ator.nomeAtor}</td>
                            <td>
                                <ul>
        `
        if (ator.idFilmes != '') {
            ator.idFilmes.forEach(filme => {

                pagHTML += `                            
                                    <li><a href="/filmes/${filme[0]}">${filme[1]}</a></li>
                `
            })
        }

    })

    pagHTML += `        
                                </ul>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>

                <footer class="w3-container w3-green">
                <h6>Generated by EngWeb2024 [<a href="/">Voltar à página principal</a>]</h6>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

//Gera página de género específico
function genGenero(genero) {
    pagHTML = `
    <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Género</title>
            <link rel="stylesheet" href="w3.css"/>
            <link rel="stylesheet" href="styles.css"/>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-red">
                    <h1>${genero.nomeGen}</h1>
                </header>
        
                <div>
                    <header class="w3-container w3-pale-red">
                        <h3>Informações</h3>
                    </header>
                    <div class="w3-container">
                        <p>Identificador: ${genero.id}</p>
                        <p>Nome: ${genero.nomeGen}</p>
                        <p>Filmes:</p>
                        <ul>
        `

        if (genero.idFilmes != '') {
            genero.idFilmes.forEach(filme => {

                pagHTML += `                            
                            <li><a href="/filmes/${filme[0]}">${filme[1]}</a></li>
                `
            })
        }

    pagHTML += `        
                        </ul>
                    </div>
                </div>

                <footer class="w3-container w3-red">
                <h6>Generated by EngWeb2024 [<a href="/generos">Voltar à lista de géneros</a>]</h6>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

//Gera página de géneros
function genGeneros(generos) {
    pagHTML = `
    <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Lista de Géneros</title>
            <link rel="stylesheet" href="w3.css"/>
            <link rel="stylesheet" href="styles.css"/>
        </head>
        
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-red">
                    <h1>Lista de géneros</h1>
                </header>
        
                <div class="w3-container">
                    <table class="w3-table w3-striped">
                        <thead>
                            <tr class="header-red"> 
                                <th>Identificador</th>
                                <th>Nome</th>
                                <th>Filmes</th>
                            </tr>
                        </thead>
                        <tbody>
    `
    generos.forEach(genero => {
        // o json server automaticamente mete um id !!
        pagHTML += `
                        <tr>
                            <td><a href="/generos/${genero.id}">${genero.id}</a></td> 
                            <td>${genero.nomeGen}</td>
                            <td>
                                <ul>
        `
        if (genero.idFilmes != '') {
            genero.idFilmes.forEach(filme => {

                pagHTML += `                            
                                    <li><a href="/filmes/${filme[0]}">${filme[1]}</a></li>
                `
            })
        }
    })

    pagHTML += `        
                                </ul>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>

                <footer class="w3-container w3-red">
                <h6>Generated by EngWeb2024 [<a href="/">Voltar à página principal</a>]</h6>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

// gerar pag de um filme específico
function genFilme(filme) {
    pagHTML = `
    <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Filme</title>
            <link rel="stylesheet" href="w3.css"/>
            <link rel="stylesheet" href="styles.css"/>
        </head>
        
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-blue">
                    <h1>${filme.title}</h1>
                </header>
        
                <div>
                    <header class=" w3-container header-blue">
                        <h3>Informações</h3>
                    </header>
                
                    <div class="w3-container">
                        <p>Id: ${filme.id}</p>
                        <p>Título: ${filme.title}</p>
                        <p>Ano: ${filme.year}</p>
                        <p>Elenco:</p>
                        <ul>
    `
    if (filme.cast != '') {
        filme.cast.forEach(castMember => {
            pagHTML += `    
                                <li><a href="/atores/${castMember[0]}">${castMember[1]}</a></li>
            `
        })
    }
    pagHTML += `        </ul>
                        <p>Géneros:</p>
                        <ul>
    `    
    if (filme.genres != '') {
        filme.genres.forEach(genre => {
            pagHTML += `    
                            <li><a href="/generos/${genre[0]}">${genre[1]}</a></li>
            `
        })
    }

    pagHTML += `        
                        </ul>
                    </div>
                </div>

                <footer class="w3-container w3-blue">
                    <h6>Generated by EngWeb2024 [<a href="/filmes">Voltar à lista de filmes</a>]</h6>
                </footer>

            </div>
        </body>
    </html>
    `
    return pagHTML
}

//todas os filmes
function genFilmes(filmes) {
    pagHTML = `
    <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Lista de filmes</title>
            <link rel="stylesheet" href="w3.css"/>
            <link rel="stylesheet" href="styles.css"/>
        </head>
        
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-blue">
                    <h1>Lista de filmes</h1>
                </header>
        
                <div class="w3-container">
                    <table class="w3-table w3-striped">
                        <thead class="w3-light-blue">
                            <tr>
                                <th>Identificador</th>
                                <th>Título</th>
                                <th>Ano</th>
                                <th>Elenco</th>
                                <th>Géneros</th>
                            </tr>
                        </thead>
                        <tbody>
    `
    filmes.forEach(filme => {
        // o json server automaticamente mete um id !!
        pagHTML += `
                        <tr>
                            <td><a href="/filmes/${filme.id}">${filme.id}</a></td> 
                            <td>${filme.title}</td>
                            <td>${filme.year}</td>
                            <td>
                                <ul>
        `
        if (filme.cast != '') {
            filme.cast.forEach(castMember => {
                pagHTML += `                            
                                    <li><a href="/atores/${castMember[0]}">${castMember[1]}</li>
                `
            })
        }
        // else {
        //         pagHTML += "                            <li>Desconhecido</li>"
        // }

        pagHTML += `        
                                </ul>
                            </td>
                            <td>
                                <ul>
        `
        if (filme.genres != '') {

            filme.genres.forEach(genre => {
                
                pagHTML += `         <li><a href="/generos/${genre[0]}">${genre[1]}</li>
                `
            })
        } 
        // else {
        //         pagHTML += "            <li>-</li>"
        // }
    })

    pagHTML += `        
                                </ul>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>

                <footer class="w3-container w3-blue">
                <h6>Generated by EngWeb2024 [<a href="/">Voltar à página principal</a>]</h6>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

http.createServer(function(req,res) {
    var filmeRegex = /^\/filmes\/[a-z0-9]{24}$/
    var generoRegex = /^\/generos\/(\d+)$/
    var atorRegex = /^\/atores\/(\d+)$/
    var w3Regex = /\/w3.css$/
    var stylesRegex = /\/styles.css$/
    var q = url.parse(req.url, true)
    console.log(q.pathname)
    if (q.pathname == "/") {
        fs.readFile("principal.html",function(erro,dados) {
            res.writeHead(200, {"Content-type":"text/html"})
            res.write(dados)
            res.end()
        })
    } else if (q.pathname == "/filmes") {
        axios.get("http://localhost:3000/filmes")
            .then(function(resp) {
                data = resp.data;
                pagHTML = genFilmes(data)
                res.writeHead(200, {"Content-Type":"text/html"})
                res.write(pagHTML)
                res.end()
            })
            .catch(error => {
                res.writeHead(500, {"Content-Type":"text/html"})
                res.write("<pre>" + error + "</pre>")
                res.end()    
            })
    } else if (filmeRegex.test(q.pathname)) {
        axios.get("http://localhost:3000" + q.pathname)
            .then(function(resp) {
                data = resp.data;
                pagHTML = genFilme(data)
                res.writeHead(200, {"Content-Type":"text/html"})
                res.write(pagHTML)
                res.end()
        })
        .catch(error => {
            res.writeHead(500, {"Content-Type":"text/html"})
            res.write("<pre>" + error + "</pre>")
            res.end()    
        })
    } else if (q.pathname == "/generos") {
        axios.get("http://localhost:3000/generos")
            .then(function(resp) {
                data = resp.data;
                pagHTML = genGeneros(data)
                res.writeHead(200, {"Content-Type":"text/html"})
                res.write(pagHTML)
                res.end()
            })
            .catch(error => {
                res.writeHead(500, {"Content-Type":"text/html"})
                res.write("<pre>" + error + "</pre>")
                res.end()    
            })
    } else if (generoRegex.test(q.pathname)) {
        axios.get("http://localhost:3000" + q.pathname)
            .then(function(resp) {
                data = resp.data;
                pagHTML = genGenero(data)
                res.writeHead(200, {"Content-Type":"text/html"})
                res.write(pagHTML)
                res.end()
        })
        .catch(error => {
            res.writeHead(500, {"Content-Type":"text/html"})
            res.write("<pre>" + error + "</pre>")
            res.end()    
        })
    } else if (q.pathname == "/atores") {
        axios.get("http://localhost:3000/atores")
            .then(function(resp) {
                data = resp.data;
                pagHTML = genAtores(data)
                res.writeHead(200, {"Content-Type":"text/html"})
                res.write(pagHTML)
                res.end()
            })
            .catch(error => {
                res.writeHead(500, {"Content-Type":"text/html"})
                res.write("<pre>" + error + "</pre>")
                res.end()    
            })
    } else if (atorRegex.test(q.pathname)) {
        axios.get("http://localhost:3000" + q.pathname)
            .then(function(resp) {
                data = resp.data;
                pagHTML = genAtor(data)
                res.writeHead(200, {"Content-Type":"text/html"})
                res.write(pagHTML)
                res.end()
        })
        .catch(error => {
            res.writeHead(500, {"Content-Type":"text/html"})
            res.write("<pre>" + error + "</pre>")
            res.end()    
        })
    } else if (w3Regex.test(q.pathname)){  // interpretar o ficheiro /w3.css
        fs.readFile('w3.css',function(err,dados) { 
            if (!err) {
                res.writeHead(200, {'Content-Type': 'text/css'})
                res.write(dados)
                res.end() // fechar pacote
            } else {
                res.writeHead(500, {"Content-Type":"text/html"})
                res.write("<pre>" + err + "</pre>")
                res.end()  
            }
        })
    } else if (stylesRegex.test(q.pathname)){  // interpretar o ficheiro /styles.css
        fs.readFile('styles.css',function(err,dados) { 
            if (!err) {
                res.writeHead(200, {'Content-Type': 'text/css'})
                res.write(dados)
                res.end() // fechar pacote
            } else {
                res.writeHead(500, {"Content-Type":"text/html"})
                res.write("<pre>" + err + "</pre>")
                res.end()  
            }
        })
    } else {
        res.writeHead(400, {'Content-Type': 'text/html; charset=utf-8'}) // tem de haver sempre else neste ifs, para n deixar a pagina pendurada, tem de haver casos de exceção // usar código de erro 400
        res.write("<p>Erro: pedido não suportado.</p>")
        res.write("<pre> Received " + q.pathname + "</pre>")
        res.end() // fechar pacote
    }
}).listen(7777)