#!/usr/bin/env python3

import json

file = open("dataset/mapa-virtual.json", "r")
bd = json.load(file)["cidades"] # NOTA: json é diferente do anterior, TPC1 era só lista de objeto, este é conjunto com objeto "cidades" (entre outros) que é por sua vez lista de objetos !!
file.close()

# sort alfabético
def chaveOrd(cidades): # chave usada como ordenacao
	return cidades["nome"]

bd.sort(key=chaveOrd)

preHTML = """
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Mapa Virtual de Cidades</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="w3.css">
		<title>Mapa Virtual de Cidades</title>
	</head>
    <body>

        <div class="w3-card-4">

            <header class="w3-container w3-green">
                <h3>Lista de Cidades</h3>
            </header>

            <div class="w3-container">
                <ul class="w3-ul" style="width:50%">
"""	

posHTML = """
				</ul>
			</div>

			<footer class="w3-container w3-green">
				<h5>Generated by MapaVirtualApp::EngWeb2024::A100709</h5>
			</footer>
		</div>
	</body>
</html>
"""

conteudoHTML = ""

for cidade in bd:
	conteudoHTML += f"""
					<li>
						<a href="http://localhost:7777/{cidade["id"]}">{cidade["nome"]} ({cidade["distrito"]})</a>
					</li>
"""
	
pagHTML = preHTML + conteudoHTML + posHTML

outFile = open("./cidadesSite/index.html","w");
outFile.write(pagHTML)
outFile.close()