#!/usr/bin/env python3

import json

file = open("dataset/mapa-virtual.json", "r")
bd = json.load(file)
file.close()

ligacoes = dict()

for ligacao in bd["ligacoes"]: # iterar sobre ligações para obter as ligações de cada cidade
    ligacoesKey = ligacao["origem"]
    if (ligacao["origem"] in ligacoes):
        ligacoes[ligacao["origem"]].append(ligacao["destino"])
    else:
        ligacoes[ligacao["origem"]] = [ligacao["destino"]]

for cidade in bd["cidades"]:
    outFile = open("cidadesSite/" + str(cidade["id"]) + ".html", "w")

    preHTML = f""" 
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Cidade: {cidade["nome"]}</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="w3.css">
	</head>

	<body>

		<div class="w3-card-4">
            <div class="w3-container">
                <header class="w3-container w3-green">
                    <h3>Informações</h3>
                </header>
                <p>Nome: {cidade["nome"]}</p>
                <p>Distrito: {cidade["distrito"]}</p>
                <p>Descrição: {cidade["descrição"]}</p>
                <p>População: {cidade["população"]}</p>
            </div>
            <div class="w3-container">
                <header class="w3-container w3-green">
                    <h3>Conexões a outras cidades</h3>
                </header>

                <div class="w3-container">
                    <ul class="w3-ul w3-card-4" style="width:50%">
"""
    
    conteudoHTML = ""

    if cidade["id"] in ligacoes:
        for cidadeligID in ligacoes[cidade["id"]]:
            currCidadeLig = bd["cidades"][int(cidadeligID[1:]) -1] # procura info em "cidades", cujo id é o da cidade adjacente
            conteudoHTML += f"""
                        <li>
                            <a href="http://localhost/7777/{cidadeligID}>{currCidadeLig["nome"]} ({currCidadeLig["distrito"]})</a>
                            <p>Distância: currCidadeLig["]
                        </li>
    """

    posHTML = f"""
			<footer class="w3-container w3-green">
				<h5>Generated by MapaVirtualApp::EngWeb2024::A100709</h5>
				<address>
					<a href=""http://localhost/7777/">Voltar a pagina principal</a>
				</address>
			</footer>
		</div>
	</body>
</html>
"""

    pagHTML = preHTML + conteudoHTML + posHTML
    outFile.write(pagHTML)
    outFile.close()