#!/usr/bin/env python3

import json

file = open("dataset/mapa-virtual.json", "r")
bd = json.load(file)
file.close()

ligacoes = dict()

for ligacao in bd["ligacoes"]: # iterar sobre ligações para obter as ligações de cada cidade
    ligacoesKey = ligacao["origem"]
    if (ligacao["origem"] in ligacoes):
        ligacoes[ligacao["origem"]].append((ligacao["destino"],ligacao["distância"]))
    else:
        ligacoes[ligacao["origem"]] = [(ligacao["destino"],ligacao["distância"])]

for cidade in bd["cidades"]:
    outFile = open("cidadesSite/" + str(cidade["id"]) + ".html", "w")

    preHTML = f""" 
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Cidade: {cidade["nome"]}</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="w3.css">
	</head>

	<body>
        <h3 style="color:green;padding: 20px; font-size:25px;font-weight: 700;"> Cidade: {cidade["nome"]} </h3>
        <div class="w3-container">
            <header class="w3-container w3-green">
                <h3>Informações</h3>
            </header>
            <div class="w3-container">
                <p>Nome: {cidade["nome"]}</p>
                <p>Distrito: {cidade["distrito"]}</p>
                <p>Descrição: {cidade["descrição"]}</p>
                <p>População: {cidade["população"]}</p>
            </div>
        </div>
        <div class="w3-container w3-padding">
            <header class="w3-container w3-green">
                <h3>Conexões a outras cidades</h3>
            </header>
"""
    conteudoHTML = ""
        
    if (cidade["id"] in ligacoes):
        conteudoHTML += f"""
            <div class="w3-container">
                <table class="w3-table w3-striped">
                    <tr>
                        <th>Cidade (Distrito)</th>
                        <th>Distância (km)</th>
                    </tr>
"""
        for (cidadeligID,distancia) in sorted(ligacoes[cidade["id"]], key=lambda x: x[1]):  # sorted por ordem alfabética das cidades com ligações
            currCidadeLig = bd["cidades"][int(cidadeligID[1:]) -1] # procura info em "cidades", cujo id é o da cidade adjacente
            conteudoHTML += f"""
                    <tr>
                        <td><a href="http://localhost:7777/{cidadeligID}">{currCidadeLig["nome"]} ({currCidadeLig["distrito"]})</a></td>
                        <td>{distancia}</td>
                    </tr>
    """
    else:
        conteudoHTML += f"""
            <div class="w3-container">
                <p> Não existe informação sobre ligações a outras cidades  </p>
            </div>
"""

    posHTML = f"""
                </table>
            </div>
        </div>
        <footer class="w3-container w3-green w3-padding">
            <h5>Generated by MapaVirtualApp::EngWeb2024::A100709</h5>
            <address>
                <a href="http://localhost:7777/">Voltar a pagina principal</a>
            </address>
        </footer>
	</body>
</html>
"""

    pagHTML = preHTML + conteudoHTML + posHTML
    outFile.write(pagHTML)
    outFile.close()