
exports.compositoresListPage = function(slist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Gestão Compositores</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Lista de compositores
                        <a class="add-button w3-btn w3-round w3-red" href="/compositores/register">+</a>   
                    </h1>   
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Período</th>
                            <th>Ações</th>
                        </tr>
                `
    for(let i=0; i < slist.length ; i++){
        pagHTML += `
                        <tr>
                            <td>${slist[i].id}</td>
                            <td>
                                <a href="/compositores/${slist[i].id}">
                                    ${slist[i].nome}
                                </a>
                            </td>
                            <td>
                                <a href="/periodos/${slist[i].periodo[0]}">
                                    ${slist[i].periodo[1]}
                                </a>
                            </td>
                            <td>
                                [<a href="/compositores/edit/${slist[i].id}">Edit</a>][<a href="/compositores/delete/${slist[i].id}">Delete</a>]
                            </td>
                        </tr>
        `
    }

    pagHTML += `
                    </table>
                </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}


exports.compositorFormPage = function(periodos,d){
    // NOTA: 
    //  nao sendo referido o url de destino de um formToJSON, os dados são enviados para o URL da pag que contém o form, aka compositors_server.js acho?
    
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Criar Compositor</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Criar compositor</h2>
                </header>
            
                <form class="w3-container" method="POST" onsubmit="prepareFormData()">
                    <fieldset>
                        <legend>Dados</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Data de nascimento</label>
                        <input class="w3-input w3-round" type="date" name="datanasc"/>
                        <label>Data de óbito</label>
                        <input class="w3-input w3-round" type="date" name="dataobito"/>
                    </fieldset>

                    <fieldset>
                        <legend>Periodo do compositor</legend>
                        <label>Período</label>
                        <select class="w3-select w3-border" name="periodo">
            `
    for (let i=0; i < periodos.length; i++) {
        pagHTML += `
                            <option value=${JSON.stringify([periodos[i]["id"], periodos[i]["nome"]])}>${periodos[i]["nome"]}</option>
        `
    }

    pagHTML +=`
                        </select>
                    </fieldset>  
                    <fieldset>
                    <legend>Vida</legend>
                        <label>Biografia</label>
                        <input class="w3-input w3-round" type="text" name="bio" maxlength = "1000"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-section" type="submit">Registar</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Voltar a compositores</a>]</h5>
                </footer>
            
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.compositorFormEditPage = function(periodos, c, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Editar Compositor</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Editar compositor</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Dados</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${c.id}"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${c.nome}"/>
                        <label>Data de nascimento</label>
                        <input class="w3-input w3-round" type="date" name="datanasc" value="${c.dataNasc}"/>
                        <label>Data de óbito</label>
                        <input class="w3-input w3-round" type="date" name="dataobito" value="${c.dataObito}"/>
                    </fieldset>
                    <fieldset>
                        <legend>Periodo do compositor</legend>
                        <label>Período</label>
                        <select class="w3-select w3-border" name="periodo">
            `
    for (let i=0; i < periodos.length; i++) {
        if (c.periodo[0] == periodos[i]["id"]) {
            pagHTML += `
                                <option value="${periodos[i]["nome"]}" selected>${periodos[i]["nome"]}</option>
            `
        } else {
            pagHTML += `
                                <option value="${periodos[i]["nome"]}">${periodos[i]["nome"]}</option>
            `
        }
    }

    pagHTML +=`
                        </select>
                    </fieldset> 
                    <fieldset>
                        <legend>Vida</legend>
                        <label>Biografia</label>
                        <input class="w3-input w3-round" type="text" name="bio" maxlength = "1000" readonly value="${c.bio}"/>
                    </fieldset> 
                    <br/>
                    <button class="w3-btn w3-purple w3-section" type="submit">Confirmar</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Voltar a compositores</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

exports.compositorPage = function(compositor, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Compositor: ${compositor.id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>${compositor.nome}</h1>
            </header>

            <div class="w3-container">
                <p><b>Id: </b> ${compositor.id}</p>
                <p><b>Nome: </b> ${compositor.nome}</p>
                <p><b>Data de nascimento: </b>${compositor.datanasc}</p>
                <p><b>Data de óbito: </b>${compositor.dataobito}</p>
                <p><b>Período: </b>                          
                    <a href="/periodos/${compositor.periodo[0]}">
                        ${compositor.periodo[1]}
                    </a>
                </p>
                <p><b>Biografia:</b></p>
                <p>${compositor.bio}</p>
            </div>
            
            <footer class="w3-container w3-teal">
                 <h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Voltar a compositores</a>]</h5>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

// -------------- Error Treatment ------------------------------
exports.compositoresErrorPage = function(errorMessage, d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Página de erro</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h2>Página de Erro</h2>
                </header>

                <div class="w3-container">
                    <p>${d}: Erro: ${errorMessage}</p>
                </div>

                <footer class="w3-container w3-teal">
                    <address><h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Voltar a compositores</a>]</h5></address>
                </footer>
            </div>
        </body>
    </html>
    `
}