
exports.periodosListPage = function(plist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Gestão Periodos</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Lista de períodos
                        <a class="add-button w3-btn w3-round w3-red" href="/periodos/register">+</a>   
                    </h1>   
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Data</th>
                            <th>Ações</th>
                        </tr>
                `
    for(let i=0; i < plist.length ; i++){
        pagHTML += `
                        <tr>
                            <td>${plist[i].id}</td>
                            <td>
                                <a href="/periodos/${plist[i].id}">
                                    ${plist[i].nome}
                                </a>
                            </td>
                            <td>${plist[i].data}</td>
                            <td>
                                [<a href="/periodos/edit/${plist[i].id}">Edit</a>][<a href="/periodos/delete/${plist[i].id}">Delete</a>]
                            </td>
                        </tr>
        `
    }

    pagHTML += `
                    </table>
                </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}


exports.periodoFormPage = function(d){
    // NOTA: 
    //  nao sendo referido o url de destino de um formToJSON, os dados são enviados para o URL da pag que contém o form, aka periodos_server.js acho?
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Criar periodo</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Criar periodo</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Dados</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Intervalo temporal</label>
                        <input class="w3-input w3-round" type="text" name="data"/>
                        </fieldset>
                        
                        <fieldset>
                            <legend>Mais informações</legend>
                            <label>Descricao</label>
                            <input class="w3-input w3-round" type="text" name="descricao" maxlength = "1000"/>
                            <input type="hidden" name="compositores" value=""/>
                        </fieldset>
                        <br/>
                    <button class="w3-btn w3-purple w3-section" type="submit">Registar</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/periodos">Voltar a periodos</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.periodoFormEditPage = function(c, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Editar periodo</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Editar periodo</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Dados</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${c.id}"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" readonly value="${c.nome}"/>
                        <label>Intervalo temporal</label>
                        <input class="w3-input w3-round" type="text" name="data" value="${c.data}"/>
                    </fieldset>
                    <fieldset>
                        <legend>Mais informações</legend>
                        <label>Descricao</label>
                        <input class="w3-input w3-round" type="text" name="descricao" maxlength = "1000" value="${c.descricao}"/>
                    </fieldset> 
                    <br/>
                    <button class="w3-btn w3-purple w3-section" type="submit">Confirmar</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/periodos">Voltar a periodos</a>]</h5>
                </footer>
            
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.periodoPage = function(periodo, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Periodo: ${periodo.id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>${periodo.nome}</h1>
            </header>

            <div class="w3-container">
                <p><b>Id: </b> ${periodo.id}</p>
                <p><b>Nome: </b> ${periodo.nome}</p>
                <p><b>Intervalo temporal: </b>${periodo.data}</p>
                <p><b>Descricao:</b></p>
                <p>${periodo.descricao}</p>
                <p><b>Compositores:</b></p>
                <ul>
    `

    if (periodo.compositores != '') {
        periodo.compositores.forEach(compositor => {
            pagHTML += `    
                    <li><a href="/compositores/${compositor[0]}">${compositor[1]}</a></li>
            `
        })
    }
    pagHTML += `
                </ul>
            </div>
            
            <footer class="w3-container w3-teal">
                 <h5>Generated by EngWeb2024 in ${d} - [<a href="/periodos">Voltar a periodos</a>]</h5>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

// -------------- Error Treatment ------------------------------
exports.periodosErrorPage = function(errorMessage, d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Página de erro</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h2>Página de Erro</h2>
                </header>

                <div class="w3-container">
                    <p>${d}: Erro: ${errorMessage}</p>
                </div>

                <footer class="w3-container w3-teal">
                    <address><h5>Generated by EngWeb2024 in ${d} - [<a href="/periodos">Voltar a periodos</a>]</h5></address>
                </footer>
            </div>
        </body>
    </html>
    `
}